version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONSUMER_THREADS: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_SESSION_TIMEOUT_MS: 10000 # Increase if necessary
      KAFKA_HEARTBEAT_INTERVAL_MS: 3000
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    volumes:
      - ./data:/var/lib/kafka/data
    networks:
      - app-network

  alarm-service:
    build: ./alarm-api
    container_name: alarm-service
    environment:
      KAFKA_BROKER: 'kafka:9092'  # Connects to the Kafka container
    depends_on:
      - kafka
    ports:
      - '3000:3000'  # Expose the port for the alarm service if needed
    networks:
      - app-network

  sleepy-human-service:
    build: ./sleepy-human-api
    container_name: sleepy-human-service
    environment:
      KAFKA_BROKER: 'kafka:9092'  # Connects to the Kafka container
    depends_on:
      - kafka
    ports:
      - '3001:3001'  # Expose the port for the sleepy human service if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
